### ISSUE TITLE
Support pure Python tasks

### ISSUE THREAD

**Issue by matiasdahl** [composable-logs/composable-logs#219]
```[tasklist]
### subtasks
- [x] https://github.com/composable-logs/mlflow/pull/62
- [x] mnist-demo: manually delete old artifacts (to allow for new format)
- [x] https://github.com/composable-logs/composable-logs/pull/222
- [x] https://github.com/composable-logs/mlflow/pull/63
- [x] https://github.com/composable-logs/mnist-digits-demo-pipeline/pull/106
- [ ] https://github.com/composable-logs/mlflow/pull/64
- [x] Check links in UI
```
